name: Ziplo Actions - launch while release

on:
  release:
    types:
      - released

jobs:
  ziplo_consignment:
    runs-on: ubuntu-latest
    name: Protect source code with Ziplo
    steps:
      - uses: actions/checkout@v2
      # Get your release tag number
      - name: App Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # You can create your archive at the beggining
      - name: Formalize folder
        run: |
          mkdir ../all-sources
          rm -rf .git .github .README.md .gitignore
          cp -TR . ../all-sources
          tar -czvf my-project-${{ steps.get_version.outputs.VERSION }}.tar.gz ../all-sources
      # Send your archive in a Ziplo Consignment Project
      - name: Test Ziplo Github Actions
        id: ziplo-action
        uses: fourfactory/ziplo-action@v2.0
        with:
          organization-token: ${{ secrets.ZIPLO_ORG_TOKEN }}
          project-token: ${{ secrets.ZIPLO_PRJ_TOKEN }}
          version: ${{ steps.get_version.outputs.VERSION }}
          filepath: my-project-${{ steps.get_version.outputs.VERSION }}.tar.gz
      # You can now continue your deployment
      - name: End process
        run: |
          echo "Code protected and application deployed"